### ISSUE TITLE
Crash when installed into the CLion IDE

### ISSUE THREAD

**Issue by daveyc** [zowe/zowe-explorer-intellij#38]
Crash when installed into CLion. This happens in the data set explorer view. 

```
java.lang.ClassCastException: class org.zowe.explorer.vfs.MFVirtualFile cannot be cast to class com.intellij.openapi.vfs.newvfs.NewVirtualFile (org.zowe.explorer.vfs.MFVirtualFile is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @78c9279c; com.intellij.openapi.vfs.newvfs.NewVirtualFile is in unnamed module of loader com.intellij.util.lang.PathClassLoader @6aceb1a5)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTablesCache$ClearTablesAndCollectNamesVisitor.getChildrenIterable(FileSymbolTablesCache.java:209)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTablesCache$ClearTablesAndCollectNamesVisitor.getChildrenIterable(FileSymbolTablesCache.java:203)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:302)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTablesCache$3.onFileChange(FileSymbolTablesCache.java:184)
	at com.jetbrains.cidr.VirtualFileChangeListener.triggerFileChanged(VirtualFileChangeListener.kt:24)
	at com.jetbrains.cidr.VirtualFileChangeListener.w(VirtualFileChangeListener.kt:40)
	at com.jetbrains.cidr.VirtualFileChangeListener.after(VirtualFileChangeListener.kt:64)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:642)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:617)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:391)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:373)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:34)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:180)
	at com.sun.proxy.$Proxy113.after(Unknown Source)
	at org.zowe.explorer.vfs.MFVirtualFileSystemModel.createChildWithAttributes(MFVirtualFileSystemModel.kt:285)
	at org.zowe.explorer.vfs.MFVirtualFileSystemModel.findOrCreate(MFVirtualFileSystemModel.kt:96)
	at org.zowe.explorer.dataops.attributes.MFRemoteAttributesServiceBase.findOrCreate(MFRemoteAttributesServiceBase.kt:83)
	at org.zowe.explorer.dataops.attributes.MFRemoteAttributesServiceBase.findOrCreateFileInternal(MFRemoteAttributesServiceBase.kt:77)
	at org.zowe.explorer.dataops.attributes.MFRemoteAttributesServiceBase.findOrCreateFileInternal(MFRemoteAttributesServiceBase.kt:26)
	at org.zowe.explorer.dataops.attributes.FsStructuringAttributesServiceBase.getOrCreateVirtualFile(FsStructuringAttributesServiceBase.kt:43)
	at org.zowe.explorer.dataops.fetch.RemoteAttributedFileFetchBase.convertResponseToFile(RemoteAttributedFileFetchBase.kt:26)
	at org.zowe.explorer.dataops.fetch.RemoteAttributedFileFetchBase.convertResponseToFile(RemoteAttributedFileFetchBase.kt:18)
	at org.zowe.explorer.dataops.fetch.RemoteFileFetchProviderBase$reload$lambda-12$$inlined$runWriteActionOnWriteThread$2$1.compute(actions.kt:71)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runWriteAction$13(ApplicationImpl.java:1024)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:1003)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1024)
	at org.zowe.explorer.dataops.fetch.RemoteFileFetchProviderBase$reload$lambda-12$$inlined$runWriteActionOnWriteThread$2.invoke(openapiUtils.kt:249)
	at org.zowe.explorer.utils.OpenapiUtilsKt.submitOnWriteThread$lambda-0(openapiUtils.kt:89)
	at com.intellij.openapi.application.constraints.ConstrainedTaskExecutor.lambda$submit$4(ConstrainedTaskExecutor.java:64)
	at com.intellij.openapi.application.constraints.BaseConstrainedExecution$Companion$scheduleWithinConstraints$1.invoke(BaseConstrainedExecution.kt:68)
	at com.intellij.openapi.application.constraints.BaseConstrainedExecution$Companion.scheduleWithinConstraints(BaseConstrainedExecution.kt:71)
	at com.intellij.openapi.application.constraints.BaseConstrainedExecution.scheduleWithinConstraints(BaseConstrainedExecution.kt:38)
	at com.intellij.openapi.application.impl.BaseExpirableExecutorMixinImpl.access$scheduleWithinConstraints$s1153900543(BaseExpirableExecutorMixinImpl.kt:12)
	at com.intellij.openapi.application.impl.BaseExpirableExecutorMixinImpl$scheduleWithinConstraints$$inlined$Runnable$1.run(Runnable.kt:19)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by KUGDev** [comment]
Hi @daveyc 
Looking into this
